import { Validator } from 'jsonschema';
const validator = new Validator();
const pdf_1300_sd_1527 = {
  id: '/1300-sd_1527',
  type: 'object',
  properties: {
    noms: { type: 'string' },
    prenoms: { type: 'string' },
    adresse: { type: 'string' },
    cp: { type: 'string' },
    ville: { type: 'string' },
    date: { type: 'Date' },
    maison_local: { type: 'boolean' },
    immeuble_local: { type: 'boolean' },
    appartement_local: { type: 'boolean' },
    autre_local: { type: 'boolean' },
    autre_local_precision: { type: 'string' },
    local_habitation: { type: 'boolean' },
    local_50p_habitation: { type: 'boolean' },
    local_xp_habitation: { type: 'boolean' },
    local_xp_chiffre: { type: 'string' },
    local_non_habita: { type: 'boolean' },
    case_proprio: { type: 'boolean' },
    case_locataire: { type: 'boolean' },
    case_autre: { type: 'boolean' },
    autre_type: { type: 'string' },
    case_fondation: { type: 'boolean' },
    etat_neuf: { type: 'boolean' },
    affet_ele: { type: 'boolean' },
    etat_neuf2: { type: 'boolean' },
    facade: { type: 'boolean' },
    etat_neuf3: { type: 'boolean' },
    nonneuf: { type: 'boolean' },
    non_plancher: { type: 'boolean' },
    neuf_2sur3_plancher: { type: 'boolean' },
    neuf_2sur3Plus_plancher: { type: 'boolean' },
    nonhuisseries_ext: { type: 'boolean' },
    neuf_2sur3_huisseries_ext: { type: 'boolean' },
    neuf_2sur3Plus_huisseries: { type: 'boolean' },
    noncloisons: { type: 'boolean' },
    neuf_2sur3_cloisons: { type: 'boolean' },
    neuf_2sur3Plus_cloisons: { type: 'boolean' },
    nonplomberie: { type: 'boolean' },
    neuf_2sur3_plomberie: { type: 'boolean' },
    neuf_2sur3Plus_plomberie: { type: 'boolean' },
    nonelec: { type: 'boolean' },
    neuf_2sur3_elec: { type: 'boolean' },
    neuf_2sur3Plus_elec: { type: 'boolean' },
    nonchauffage: { type: 'boolean' },
    neuf_2sur3_chauffage: { type: 'boolean' },
    neuf_2sur3Plus_chauffage: { type: 'boolean' },
    attest_period2ans: { type: 'boolean' },
    attest_travsurelev: { type: 'boolean' },
    attest_travqualiteener: { type: 'boolean' },
    attest_tvareduite: { type: 'boolean' },
    signature_af_image: { type: 'string' },
    interno: { type: 'string' },
  },
  required: [
    'noms',
    'prenoms',
    'adresse',
    'cp',
    'ville',
    'date',
    'maison_local',
    'immeuble_local',
    'appartement_local',
    'autre_local',
    'autre_local_precision',
    'local_habitation',
    'local_50p_habitation',
    'local_xp_habitation',
    'local_xp_chiffre',
    'local_non_habita',
    'case_proprio',
    'case_locataire',
    'case_autre',
    'autre_type',
    'case_fondation',
    'etat_neuf',
    'affet_ele',
    'etat_neuf2',
    'facade',
    'etat_neuf3',
    'nonneuf',
    'non_plancher',
    'neuf_2sur3_plancher',
    'neuf_2sur3Plus_plancher',
    'nonhuisseries_ext',
    'neuf_2sur3_huisseries_ext',
    'neuf_2sur3Plus_huisseries',
    'noncloisons',
    'neuf_2sur3_cloisons',
    'neuf_2sur3Plus_cloisons',
    'nonplomberie',
    'neuf_2sur3_plomberie',
    'neuf_2sur3Plus_plomberie',
    'nonelec',
    'neuf_2sur3_elec',
    'neuf_2sur3Plus_elec',
    'nonchauffage',
    'neuf_2sur3_chauffage',
    'neuf_2sur3Plus_chauffage',
    'attest_period2ans',
    'attest_travsurelev',
    'attest_travqualiteener',
    'attest_tvareduite',
    'signature_af_image',
    'interno',
  ],
};
const produits = {
  id: '/produits',
  type: 'object',
  properties: {
    total: {
      type: 'object',
      prixAcompte: { type: 'number' },
      prixHTTotal: { type: 'number' },
      prixReduc: { type: 'number' },
      prixTTCTotal: { type: 'number' },
    },
  },
};
const rapports = {
  id: '/rapports',
  type: 'object',
  properties: {
    rapports: {
      type: 'object',
      after: { type: 'object' },
      before: { type: 'object' },
      textarea: { type: 'object' },
      idAdmins: { type: 'object' },
    },
  },
};

const paiements = {
  id: '/paiements',
  type: 'object',
  properties: {
    rapports: {
      type: 'object',
      after: { type: 'object' },
      before: { type: 'object' },
      textarea: { type: 'object' },
      idAdmins: { type: 'object' },
    },
  },
};

const devis = {
  id: '/devis',
  type: 'object',
  properties: {
    id: { type: 'number' },
    id_inter: { type: 'number' },
    statut: { type: 'string' },
    apiURL: { type: 'string' },
    document_id: { type: 'string' },
    type_document: { type: 'string' },

    noms_inter: { type: 'string' },
    prenoms_inter: { type: 'string' },
    ville_inter: { type: 'string' },
    codepostal_inter: { type: 'string' },
    adresse_inter: { type: 'string' },
    adresse_complement1_inter: { type: 'string' },
    adresse_complement2_inter: { type: 'string' },
    adresse_complement3_inter: { type: 'string' },
    digicode_inter: { type: 'string' },
    date_inter: { type: 'string' },
    urgence: { type: 'string' },

    noms_devis: { type: 'string' },
    prenoms_devis: { type: 'string' },
    ville_devis: { type: 'string' },
    codepostal_devis: { type: 'string' },
    adresse_devis: { type: 'string' },
    adresse_complement1_devis: { type: 'string' },
    adresse_complement2_devis: { type: 'string' },
    adresse_complement3_devis: { type: 'string' },

    digicode_devis: { type: 'string' },
    date_devis: { type: 'string' },
    statutFacture: { type: 'string' },

    mail: { type: 'string' },
    telephone: { type: 'string' },
    signature: { type: 'string' },
    produits: { $ref: '/produits' },
    paiements: { $ref: '/paiements' },
    rapports: { $ref: '/rapports' },
    totauxPaiements: { type: 'number' },
    resteAPayer: { type: 'number' },
    montant_pourcentage_exigible: { type: 'number' },
    montant_paiement_multiple: { type: 'number' },
    modalites: { type: 'string' },
  },
  required: [],
};

validator.addSchema(pdf_1300_sd_1527, '/1300-sd_1527');
validator.addSchema(produits, '/produits');
validator.addSchema(rapports, '/rapports');
validator.addSchema(paiements, '/paiements');
validator.addSchema(devis, '/devis');

export { validator, pdf_1300_sd_1527, produits, rapports, paiements, devis };
